-- BORRAR TABLAS
DROP TABLE IF EXISTS CITAS;
DROP TABLE IF EXISTS TRAJES;
DROP TABLE IF EXISTS USUARIOS;
DROP TABLE IF EXISTS TALLERES;
DROP TABLE IF EXISTS CLIENTES;


-- TABLA CLIENTES --

CREATE TABLE CLIENTES (
id_cliente INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(100) NOT NULL,
SUPERPODER VARCHAR(100),
COLORES VARCHAR(100),
TIPO VARCHAR(10) NOT NULL,
CHECK (TIPO IN ('HEROE', 'VILLANO'))
);


-- TABLA TRAJES --

CREATE TABLE TRAJES (
ID_TRAJE INT AUTO_INCREMENT PRIMARY KEY,
ID_CLIENTE INT NOT NULL,
NOMBRE VARCHAR(100),
ESTADO VARCHAR(50) NOT NULL,
CHECK (ESTADO IN ('DISEÑO', 'COSTURA', 'TALLER')),
FOREIGN KEY (ID_CLIENTE)
    REFERENCES CLIENTES(ID_CLIENTE)
    ON DELETE CASCADE
);


-- TABLA TALLERES --

CREATE TABLE TALLERES (
ID_TALLER INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE_SALA VARCHAR(100),
TIPO_SALA VARCHAR(50) NOT NULL,
CHECK (TIPO_SALA IN ('DISEÑO', 'COSTURA', 'PRUEBAS'))
);


-- TABLA CITAS --

CREATE TABLE CITAS (
ID_CITA INT AUTO_INCREMENT PRIMARY KEY,
ID_CLIENTE INT NOT NULL,
ID_TRAJE INT NOT NULL,
ID_TALLER INT NOT NULL,
FECHA DATE NOT NULL,
HORA VARCHAR(5) NOT NULL,
DURACION INT DEFAULT 1,

FOREIGN KEY (ID_CLIENTE)
    REFERENCES CLIENTES(ID_CLIENTE)
    ON DELETE CASCADE,

FOREIGN KEY (ID_TRAJE)
    REFERENCES TRAJES(ID_TRAJE)
    ON DELETE CASCADE,

FOREIGN KEY (ID_TALLER)
    REFERENCES TALLERES(ID_TALLER)
);


-- TABLA USUARIOS --

CREATE TABLE USUARIOS (
ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
ID_CLIENTE INT,
USERNAME VARCHAR(100),
PASSWORD VARCHAR(200) NOT NULL UNIQUE,

FOREIGN KEY (ID_CLIENTE)
    REFERENCES CLIENTES(ID_CLIENTE)
    ON DELETE CASCADE
);


-- INSERTAR CLIENTES --

INSERT INTO CLIENTES (NOMBRE, SUPERPODER, COLORES, TIPO) VALUES
('Spiderman', 'Trepar muros', 'Rojo/Azul', 'HEROE'),
('Batman', 'Inteligencia', 'Negro', 'HEROE'),
('Joker', 'Caos', 'Morado/Verde', 'VILLANO');


-- INSERTAR TRAJES --

INSERT INTO TRAJES (ID_CLIENTE, NOMBRE, ESTADO) VALUES
(1, 'Traje clásico', 'DISEÑO'),
(2, 'Traje negro', 'COSTURA'),
(3, 'Traje sigilo', 'TALLER');


-- INSERTAR TALLERES --

INSERT INTO TALLERES (NOMBRE_SALA, TIPO_SALA) VALUES
('Milán', 'DISEÑO'),
('París', 'COSTURA'),
('Madrid', 'PRUEBAS');


-- INSERTAR CITAS --

INSERT INTO CITAS (ID_CLIENTE, ID_TRAJE, ID_TALLER, FECHA, HORA, DURACION) VALUES
(1, 1, 1, '2026-04-10', '10:00', 1),
(2, 2, 2, '2026-04-10', '11:00', 1),
(3, 3, 3, '2026-04-11', '13:00', 1);

-- INSERTAR USUARIOS --
INSERT INTO USUARIOS (username, password) VALUES ('edna', '1234');